friestt

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -2,18 +2,18 @@ name: 01 - Building Blocks
 
 on: push 
 jobs: 
-  echo-hello
-    runs:ubuntu-latest
-     steps:
-        - name: Say Hello 
-          run: echo " Hello, World!"
-  echo-goodbye:
-     runs-on: ubuntu-latest
+    echo-hello:
+      runs-on: ubuntu-latest
       steps:
-       - name: Failed steps:
-         run: |
-          echo "I Will fail"
-          exit 0
-       - name: Say goodbye
+        - name: Say Hello 
+          run: echo "Hello, World!"
+    echo-goodbye:
+      runs-on: ubuntu-latest
+      steps:
+        - name: Failed step:
+          run: |
+            echo "I Will fail"
+            exit 1
+        - name: Say goodbye
           run: echo "Goodbye!"
 
